export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT_STALE: 'CONFLICT_STALE',
  CONFLICT_UNIQUE: 'CONFLICT_UNIQUE',
  CONFLICT_REFERENCED: 'CONFLICT_REFERENCED',
  CONFLICT_NON_EMPTY: 'CONFLICT_NON_EMPTY',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  MAGIC_BYTES_MISMATCH: 'MAGIC_BYTES_MISMATCH',
  SEMANTIC_ERROR: 'SEMANTIC_ERROR',
  SCHEMA_MISMATCH: 'SCHEMA_MISMATCH',
  BACKUP_CHECKSUM_MISMATCH: 'BACKUP_CHECKSUM_MISMATCH',
  RESTORE_FAILED: 'RESTORE_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;

export interface ErrorEnvelope {
  error: {
    code: ErrorCode;
    message: string;
    fields?: Record<string, string[]>;
    request_id?: string;
  };
}
